# Databricks notebook source
# MAGIC %md
# MAGIC # Econ Data Pipeline: Delta Lake & Time Travel Demo
# MAGIC This notebook demonstrates how to connect Databricks to your S3 bucket containing the Delta Lake tables
# MAGIC generated by the ingestion pipeline, query them, and utilize Delta's "Time Travel" feature.

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Configure AWS S3 Access
# MAGIC To read the Delta tables from S3, Databricks needs credentials to access your bucket.
# MAGIC In a production environment, this should be done using Databricks Instance Profiles or Secret Scopes.
# MAGIC For a personal free account/demo, we can set the Spark configuration directly.

# COMMAND ----------

import os

# Replace with your actual S3 bucket name where Delta tables are stored
# For example, if your DELTA_S3_PATH was set to 's3a://econ-pipeline-raw-data-dev/delta_lake'
S3_BUCKET = "econ-pipeline-raw-data-dev"
DELTA_BASE_PATH = f"s3a://{S3_BUCKET}/delta_lake"

# To keep credentials secure in the free Community Edition (which lacks Secret Scopes),
# we create Databricks UI widgets. You will enter your keys at the top of the notebook.
dbutils.widgets.text("1_aws_access_key", "", "AWS Access Key")
dbutils.widgets.text("2_aws_secret_key", "", "AWS Secret Key")

aws_access_key = dbutils.widgets.get("1_aws_access_key")
aws_secret_key = dbutils.widgets.get("2_aws_secret_key")

if not aws_access_key or not aws_secret_key:
    raise ValueError("Please enter your AWS credentials in the widgets at the top of the notebook!")

# AWS credentials must be configured on Spark context for the `s3a://` protocol
spark.conf.set("fs.s3a.access.key", aws_access_key)
spark.conf.set("fs.s3a.secret.key", aws_secret_key)
spark.conf.set("fs.s3a.endpoint", "s3.amazonaws.com")

# Note: On newer Databricks clusters AWS credential pass-through is handled differently
# but for a free community account Spark configs should work.

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Read the Latest Delta Table
# MAGIC Let's read the `bea_nipa_observations` table that was created by our PySpark `delta_writer.py` pipeline.

# COMMAND ----------

table_path_bea = f"{DELTA_BASE_PATH}/bea/nipa_observations"

print(f"Reading Delta table from: {table_path_bea}")

# Standard PySpark DataFrame read from the Delta data source
df_bea = spark.read.format("delta").load(table_path_bea)

# Databricks `display` function provides native UI interactions and charting
display(df_bea)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Delta Table History
# MAGIC Delta Lake automatically keeps a transaction log of every operation (INSERT, UPDATE, DELETE, MERGE, OPTIMIZE) performed on the table. Let's inspect the history.

# COMMAND ----------

from delta.tables import DeltaTable

# Access the DeltaTable instance and compute its history
delta_table = DeltaTable.forPath(spark, table_path_bea)

# Display the history of the Delta table (the transaction log)
display(delta_table.history())

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. Time Travel (VERSION AS OF / TIMESTAMP AS OF)
# MAGIC With Delta Lake Time Travel, you can query older snapshots of the table. This is extremely valuable for reproducing machine learning models (to avoid look-ahead bias) and auditing data changes over time.

# COMMAND ----------

# Get the history to find available versions
history_df = delta_table.history().collect()

if len(history_df) >= 2:
    # If we have multiple versions, let's compare the latest version with an older one
    latest_version = history_df[0]["version"]
    older_version = history_df[-1]["version"] # The initial creation version, usually 0
    
    print(f"Latest version: {latest_version}")
    print(f"Older version: {older_version}")
    
    # Query the table AS OF the older version using the dataframe API
    df_older = spark.read.format("delta").option("versionAsOf", older_version).load(table_path_bea)
    
    print(f"Row count at version {older_version}: {df_older.count():,}")
    print(f"Row count at version {latest_version}: {df_bea.count():,}")
    
    # You can also time travel using timestamps:
    # df_timestamp = spark.read.format("delta").option("timestampAsOf", "2024-03-01 00:00:00").load(table_path_bea)
else:
    print("Table only has 1 version. Run the local delta_writer.py pipeline again with new data to create more versions!")
    
    # Example of Time Travel syntax
    print("\nDisplaying Time Travel query (if version 0 exists):")
    df_v0 = spark.read.format("delta").option("versionAsOf", 0).load(table_path_bea)
    display(df_v0)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 5. SQL Syntax Example
# MAGIC We can also use Databricks SQL to query the Delta table using standard SQL syntax, including Time Travel natively in the SQL dialect.

# COMMAND ----------

# Register the table as a temporary view to query it with SQL
spark.sql(f"CREATE OR REPLACE TEMPORARY VIEW bea_nipa_observations_view USING delta LOCATION '{table_path_bea}'")

# Optionally, you can pass python variables to SQL cells using spark.conf
spark.conf.set("demo.path", table_path_bea)

# COMMAND ----------

# MAGIC %sql
# MAGIC -- Regular SQL query
# MAGIC SELECT period_date, series_name, value, ingested_at
# MAGIC FROM bea_nipa_observations_view
# MAGIC ORDER BY ingested_at DESC
# MAGIC LIMIT 10

# COMMAND ----------

# MAGIC %sql
# MAGIC -- SQL Time Travel query (using VERSION AS OF)
# MAGIC -- Here we query the raw files directly by path so we can use VERSION AS OF.
# MAGIC SELECT *
# MAGIC FROM delta.`${demo.path}` VERSION AS OF 0
# MAGIC LIMIT 5

# COMMAND ----------

# MAGIC %md
# MAGIC ## 6. Clean Up (Optional)
# MAGIC You can run OPTIMIZE to compact smaller parquet files and VACUUM to remove old files no longer needed for time travel based on retention policy.

# COMMAND ----------

# MAGIC %sql
# MAGIC -- OPTIMIZE compacts files
# MAGIC OPTIMIZE delta.`${demo.path}` ZORDER BY (table_key, series_name);
# MAGIC 
# MAGIC -- VACUUM removes files older than the retention period (default 7 days)
# MAGIC -- VACUUM delta.`${demo.path}` RETAIN 168 HOURS;
